version: "3.8"
services:
  rabbitmq1:
    image: rabbitmq:3.13.0-management-alpine
    hostname: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbitmq-haproxy/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./rabbitmq-haproxy/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq-haproxy/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536

  rabbitmq2:
    image: rabbitmq:3.13.0-management-alpine
    hostname: rabbitmq2
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./rabbitmq-haproxy/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./rabbitmq-haproxy/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq-haproxy/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536

  rabbitmq3:
    image: rabbitmq:3.13.0-management-alpine
    hostname: rabbitmq3
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./rabbitmq-haproxy/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./rabbitmq-haproxy/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq-haproxy/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536
  
  rabbitmq4:
    image: rabbitmq:3.13.0-management-alpine
    hostname: rabbitmq4
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./rabbitmq-haproxy/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./rabbitmq-haproxy/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq-haproxy/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536
  
  rabbitmq5:
    image: rabbitmq:3.13.0-management-alpine
    hostname: rabbitmq5
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./rabbitmq-haproxy/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./rabbitmq-haproxy/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq-haproxy/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536

  rabbitmq6:
    image: rabbitmq:3.13.0-management-alpine
    hostname: rabbitmq6
    restart: always
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./rabbitmq-haproxy/rabbitmq.conf:/etc/rabbitmq/conf.d/10-defaults.conf
      - ./rabbitmq-haproxy/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./rabbitmq-haproxy/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536

  haproxy:
    image: haproxy:lts-bookworm
    restart: always
    user: root
    volumes:
      - ./rabbitmq-haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
      - rabbitmq4
      - rabbitmq5
      - rabbitmq6
    ports:
      - 15672:15672 # RabbitMQ Management
      - 5672:5672 # RabbitMQ
